<?php

namespace AppBundle\Repository;

/**
 * PlantaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantaRepository extends \Doctrine\ORM\EntityRepository
{
}
