<?php

namespace AppBundle\Repository;

/**
 * ProoveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProoveedorRepository extends \Doctrine\ORM\EntityRepository
{
}
